#!/usr/bin/env python

import pathlib
import subprocess
import sys

project_dir = (pathlib.Path(__file__) / ".." / "..").resolve()

version = sys.argv[1]
(project_dir / "VERSION").write_text(version + "\n")

subprocess.check_call(["git", "add", "VERSION"], cwd=project_dir)
subprocess.check_call(
    ["git", "commit", "-m", f"Updates VERSION: {version}"], cwd=project_dir
)
subprocess.check_call(["git", "tag", f"v{version}"], cwd=project_dir)

# manually push commit and tags
